apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
  labels:
    app: addressbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook
        image: santhosh0637/addressbook
        ports:
        - containerPort: 80
